DROP TABLE IF EXISTS VIDEO CASCADE;
DROP TABLE IF EXISTS VIDEO_CATEGORY CASCADE;
CREATE TABLE VIDEO (id INTEGER NOT NULL, file_path VARCHAR(255), title VARCHAR(255), category_id INTEGER, PRIMARY KEY (id));
CREATE TABLE VIDEO_CATEGORY (id INTEGER NOT NULL, name VARCHAR(255), PRIMARY KEY (id));
ALTER TABLE VIDEO ADD CONSTRAINT FK_VIDEO_CATEGORY_ID FOREIGN KEY (category_id) REFERENCES VIDEO_CATEGORY;

INSERT INTO VIDEO_CATEGORY(id, name) VALUES (1, 'Exercise');
INSERT INTO VIDEO_CATEGORY(id, name) VALUES (2, 'Education');
INSERT INTO VIDEO_CATEGORY(id, name) VALUES (3, 'Recipe');